package com.example.cmw_simulator

import android.util.Log
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import okhttp3.MediaType.Companion.toMediaType
import okhttp3.OkHttpClient
import okhttp3.Request
import okhttp3.RequestBody.Companion.toRequestBody

/**
 * Sends RC JSON AST to the local JVM Compiler Server and receives compiled RC binary.
 * The server runs on the host machine at http://10.0.2.2:8080 (emulator localhost mapping).
 */
object RcCompiler {

    private val client = OkHttpClient.Builder()
        .connectTimeout(30, java.util.concurrent.TimeUnit.SECONDS)
        .readTimeout(120, java.util.concurrent.TimeUnit.SECONDS)
        .build()

    private const val BACKEND_URL = "http://10.0.2.2:8080/api/v1/widget/generate"

    /**
     * Posts the Gemini-generated JSON AST string to the local compiler server
     * and returns the compiled RC bytes.
     *
     * @param jsonAst The RC JSON AST generated by Gemini
     * @return Compiled RC ByteArray, or null on failure
     */
    suspend fun compileJsonToRc(jsonAst: String): ByteArray? =
        withContext(Dispatchers.IO) {
            try {
                val body = jsonAst.toRequestBody("application/json; charset=utf-8".toMediaType())
                val request = Request.Builder()
                    .url(BACKEND_URL)
                    .post(body)
                    .build()

                client.newCall(request).execute().use { response ->
                    if (response.isSuccessful) {
                        val bytes = response.body?.bytes()
                        Log.d("RcCompiler", "Received ${bytes?.size ?: 0} RC bytes from compiler")
                        bytes
                    } else {
                        val errorBody = response.body?.string()?.take(500) ?: "unknown"
                        Log.e("RcCompiler", "Compiler error ${response.code}: $errorBody")
                        null
                    }
                }
            } catch (e: Exception) {
                Log.e("RcCompiler", "Failed to reach compiler server at $BACKEND_URL", e)
                null
            }
        }

    /**
     * Legacy: Posts DSL code to the old /compile-rc endpoint.
     * Kept for backward compatibility with Paste DSL mode.
     */
    suspend fun fetchRcBytesFromBackend(dslCode: String): ByteArray? =
        withContext(Dispatchers.IO) {
            try {
                val body = dslCode.toRequestBody("text/plain; charset=utf-8".toMediaType())
                val request = Request.Builder()
                    .url("http://10.0.2.2:8080/compile-rc")
                    .post(body)
                    .build()

                client.newCall(request).execute().use { response ->
                    if (response.isSuccessful) {
                        val bytes = response.body?.bytes()
                        Log.d("RcCompiler", "Received ${bytes?.size ?: 0} bytes from backend")
                        bytes
                    } else {
                        val errorBody = response.body?.string()?.take(500) ?: "unknown"
                        Log.e("RcCompiler", "Backend error ${response.code}: $errorBody")
                        null
                    }
                }
            } catch (e: Exception) {
                Log.e("RcCompiler", "Failed to reach backend", e)
                null
            }
        }
}
